In [1]:
# Gives the discrete, linear convolution of two one-dimensional sequences.
# some goodies
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math

In [6]:
#input the two 1D array
str_arr_I = raw_input('inser only the values of the first 1D array with the space between them:').split(' ') 
Iin=0.0* np.ones(len(str_arr_I))
for i,j in zip (str_arr_I, xrange(len(str_arr_I))):    
    Iin[j]=i
str_arr_k = raw_input('inser only values of the second 1D array with the space between them:').split(' ') 
k=0.0* np.ones(len(str_arr_k))
for i,j in zip (str_arr_k, xrange(len(str_arr_k))):    
    k[j]=i

inser only the values of the first 1D array with the space between them:1 2 3 4
inser only values of the second 1D array with the space between them:1 2 3


In [7]:
# convolution of two arrays with built-in library
T=np.convolve(Iin,k, 'full')
print(T)
T=np.convolve(Iin,k, 'same')
print(T)

[  1.   4.  10.  16.  17.  12.]
[  4.  10.  16.  17.]


In [8]:
# convolution of two arrays with my code
TT=[0]*(len(k)-1)
I=np.concatenate((TT,Iin), axis=0)

Result=0.0* np.ones(len(I))
#Result.astype(int)
for i in xrange(len(I)):    
    con = 0                     
    for j in xrange (len(k)):
        if i+j>len(I)-1:
            con += 0*k[(len(k))-j] 
        else:
            con += I[i+j] * k[(len(k)-1)-j] 
    Result[i]=con
print(Result)

[  1.   4.  10.  16.  17.  12.]


In [9]:
# convolution of two arrays with my code for "same" mode
mid_idx=0
length=0
if len(Iin)>len(k):
    length=len(Iin)
else:
    length=len(k)
mid_idx=int(len(Result)/2) 
frnt_idx=int(mid_idx-np.ceil(length/2))
end_idx=frnt_idx+length
idx=np.arange(frnt_idx,end_idx)
same=0.0* np.ones(len(idx))
for i,j in zip (idx, xrange(len(idx))):
    d=Result[i]
    same[j]=d
    
print(same)

[  4.  10.  16.  17.]
