In [287]:
# Gives the discrete, linear convolution of two one-dimensional sequences.
# some goodies
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math

In [288]:
#input the two 1D array
str_arr_I = raw_input('insert only the values of the first 1D array with the space between them:').split(' ') 
Iin=0.0* np.ones(len(str_arr_I))
for i,j in zip (str_arr_I, xrange(len(str_arr_I))):    
    Iin[j]=i
str_arr_k = raw_input('insert only values of the second 1D array with the space between them:').split(' ') 
k=0.0* np.ones(len(str_arr_k))
for i,j in zip (str_arr_k, xrange(len(str_arr_k))):    
    k[j]=i

insert only the values of the first 1D array with the space between them:1 2 3 4 5 6
insert only values of the second 1D array with the space between them:6 7 8


In [289]:
# convolution of two arrays with built-in library
T=np.convolve(Iin,k, 'full')
print(T)
T=np.convolve(Iin,k, 'same')
print(T)

[   6.   19.   40.   61.   82.  103.   82.   48.]
[  19.   40.   61.   82.  103.   82.]


In [290]:
# convolution of two arrays with my code for "full" mode
TT=[0]*(len(k)-1)
I=np.concatenate((TT,Iin), axis=0)

Result=0.0* np.ones(len(I))
for i in xrange(len(I)):    
    con = 0                     
    for j in xrange (len(k)):
        if i+j>len(I)-1:
            con += 0*k[(len(k))-j] 
        else:
            con += I[i+j] * k[(len(k)-1)-j] 
    Result[i]=con
print(Result)

[   6.   19.   40.   61.   82.  103.   82.   48.]


In [291]:
# convolution of two arrays with my code for "same" mode

length_same=0
if len(Iin)>len(k):
    length_same=len(Iin)
else:
    length_same=len(k)
length_full=len(Result)
offset=length_full-length_same
offset_from_eachend=offset/2
frnt_idx=int(offset_from_eachend)
end_idx=frnt_idx+length_same
idx=np.arange(frnt_idx,end_idx)
same=0.0* np.ones(len(idx))
for i,j in zip (idx, xrange(len(idx))):
    d=Result[i]
    same[j]=d
    
print(same)

[  19.   40.   61.   82.  103.   82.]


In [293]:
# convolution of two arrays with my code without any 'for'loop
kT=k[::-1]   
if len(Iin)<len(k):
    kT=Iin[::-1]    
kT0=kT
kT1=kT
if len(k)!=len(Iin): 
    kT_=[0]*abs(len(k)-len(Iin))
    kT0=np.concatenate((kT_,kT), axis=0)
    kT1=np.concatenate((kT,kT_), axis=0)
    
length_s=0
if len(Iin)>len(k):
    length_s=len(Iin)
else:
    length_s=len(k)
    
if len(Iin)<len(k):
    Iin=k
    
M,T=np.meshgrid(Iin,Iin)
il=np.tril(M[:(len(kT)-1),:])
iu=np.triu(M)
mask = il>0
mask_1 = iu>0
justified_mask = np.sort(mask,1)
justified_mask_1 = np.sort(mask_1,1)
justified_mask = justified_mask[:,::]
justified_mask_1 = justified_mask_1[:,::-1]
out = np.zeros_like(il[:,:]) 
out_1 = np.zeros_like(iu)
out[justified_mask] = il[:,:][mask]
out_1[justified_mask_1] = iu[mask_1]
Rr=np.concatenate((np.dot(out,kT0),np.dot(kT1,out_1)),axis=0)
print("for full mode {}".format(Rr) )
length_f=len(Rr)
off=length_f-length_s
off_eachend=off/2
f_idx=int(off_eachend)
e_idx=f_idx+length_s
Sr=Rr[f_idx:e_idx]
print("for same mode {}".format(Sr))

for full mode [   6.   19.   40.   61.   82.  103.   82.   48.]
for same mode [  19.   40.   61.   82.  103.   82.]
