In [38]:
# Gives the discrete, linear convolution of two one-dimensional sequences.
# some goodies
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math

In [39]:
#input the two 1D array
str_arr_I = raw_input('insert only the values of the first 1D array with the space between them:').split(' ') 
Iin=0.0* np.ones(len(str_arr_I))
for i,j in zip (str_arr_I, xrange(len(str_arr_I))):    
    Iin[j]=i
str_arr_k = raw_input('insert only values of the second 1D array with the space between them:').split(' ') 
k=0.0* np.ones(len(str_arr_k))
for i,j in zip (str_arr_k, xrange(len(str_arr_k))):    
    k[j]=i

insert only the values of the first 1D array with the space between them:1 2 3 4
insert only values of the second 1D array with the space between them:1 2 3


In [40]:
# convolution of two arrays with built-in library
T=np.convolve(Iin,k, 'full')
print(T)
T=np.convolve(Iin,k, 'same')
print(T)

[  1.   4.  10.  16.  17.  12.]
[  4.  10.  16.  17.]


In [41]:
# convolution of two arrays with my code for "full" mode
TT=[0]*(len(k)-1)
I=np.concatenate((TT,Iin), axis=0)

Result=0.0* np.ones(len(I))
for i in xrange(len(I)):    
    con = 0                     
    for j in xrange (len(k)):
        if i+j>len(I)-1:
            con += 0*k[(len(k))-j] 
        else:
            con += I[i+j] * k[(len(k)-1)-j] 
    Result[i]=con
print(Result)

[  1.   4.  10.  16.  17.  12.]


In [46]:
# convolution of two arrays with my code for "same" mode

length_same=0
if len(Iin)>len(k):
    length_same=len(Iin)
else:
    length_same=len(k)
length_full=len(Result)
offset=length_full-length_same
offset_from_eachend=offset/2
frnt_idx=int(offset_from_eachend)
end_idx=frnt_idx+length_same
idx=np.arange(frnt_idx,end_idx)
same=0.0* np.ones(len(idx))
for i,j in zip (idx, xrange(len(idx))):
    d=Result[i]
    same[j]=d
    
print(same)

[  4.  10.  16.  17.]


In [75]:
# convolution of two arrays without for loop
kT=k[: : -1]
if len(k)!=len(Iin): 
    kT_=[0]*abs(len(k)-len(Iin))
    kT=np.concatenate((kT,kT_), axis=0)
M,T=np.meshgrid(Iin,Iin)
iu=np.triu(M)
mask = iu>0
justified_mask = np.sort(mask,1)
justified_mask = justified_mask[:,::-1]
out = np.zeros_like(iu) 
out[justified_mask] = iu[mask]
dot=np.dot(kT,out)
print(dot)

[ 10.  16.  17.  12.]
